#SPDX-License-Identifier: MIT-0
---
- name: Install Podman
  ansible.builtin.dnf:
    name:
      - podman
    state: present
  become: yes

- name: Install Podman Compose
  ansible.builtin.dnf:
    name:
      - podman-compose
    state: present
  become: yes

- name: Install Podman Docker
  ansible.builtin.dnf:
    name:
      - podman-docker
    state: present
  become: yes
# tasks file for podman-desktop
